providerCode=cohere
paramApplier=info.mengnan.dialogerai.rag.container.factory.HuggingFaceApplierModelFactory

EMBEDDING=dev.langchain4j.model.cohere.CohereEmbeddingModel
SCORING=dev.langchain4j.model.cohere.CohereScoringModel
