providerCode=huggingFace
paramApplier=info.mengnan.dialogerai.rag.container.factory.CohereParamApplierModelFactory

CHAT=dev.langchain4j.model.openai.OpenAiChatModel
STREAMING_CHAT=dev.langchain4j.model.openai.OpenAiStreamingChatModel
EMBEDDING=dev.langchain4j.model.huggingface.HuggingFaceEmbeddingModel